// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzcMegUm7ANJirYRRv8EYeo78qpdTdy-c',
    appId: '1:501384975705:android:891431603bf26d96212848',
    messagingSenderId: '501384975705',
    projectId: 'fuelauth-9ff03',
    storageBucket: 'fuelauth-9ff03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVm6DgE6WqxPwROoL4wHYFJHDmt-W-x_E',
    appId: '1:501384975705:ios:1c20a91726a59c2a212848',
    messagingSenderId: '501384975705',
    projectId: 'fuelauth-9ff03',
    storageBucket: 'fuelauth-9ff03.appspot.com',
    iosBundleId: 'com.example.fuelSystem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSL1u9iy9a71RqXD8lh7QmtARGs9U2pI0',
    appId: '1:501384975705:web:933aaaf7790268d2212848',
    messagingSenderId: '501384975705',
    projectId: 'fuelauth-9ff03',
    authDomain: 'fuelauth-9ff03.firebaseapp.com',
    storageBucket: 'fuelauth-9ff03.appspot.com',
    measurementId: 'G-2R4QCPGD8D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVm6DgE6WqxPwROoL4wHYFJHDmt-W-x_E',
    appId: '1:501384975705:ios:1c20a91726a59c2a212848',
    messagingSenderId: '501384975705',
    projectId: 'fuelauth-9ff03',
    storageBucket: 'fuelauth-9ff03.appspot.com',
    iosBundleId: 'com.example.fuelSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSL1u9iy9a71RqXD8lh7QmtARGs9U2pI0',
    appId: '1:501384975705:web:acada8f16deb71ea212848',
    messagingSenderId: '501384975705',
    projectId: 'fuelauth-9ff03',
    authDomain: 'fuelauth-9ff03.firebaseapp.com',
    storageBucket: 'fuelauth-9ff03.appspot.com',
    measurementId: 'G-ZRBRLJ4XX4',
  );

}